### ISSUE TITLE
Assignment 4 question

### ISSUE THREAD

**Issue by bdonovan7** [tegge-classroom/STAT2984-2018#28]
Does anyone know how to extract column names and create a list of lists for the data and a dictionary of lists for the data for the assignment? I copied the code from the housing prices data and changed it to fit the hurricane data, but it did not work.

**Comment by ategge** [comment]
When you say the code did not work, do you mean you received an error or the output was not what you expected? If the first, please include the error message.

**Comment by maxh95** [comment]
You can use if statements I believe.  For example:
        if name != "-----":
            name_list.append(name)

This helps deal with your missing values in the data. It doesn't quite answer your question about reading data to a list of lists or dictionary but that is how I dealt with that issue when I had it.
