### ISSUE TITLE
Reading in the Data

### ISSUE THREAD

**Issue by abbyt99** [tegge-classroom/STAT2984-2018#33]
I am trying to read in the data and it keeps giving me an error that it cannot convert a string to a float.

**Comment by cahicks** [comment]
In order for me to be able to read the data, I had to first import some things like this import 
matplotlib.pyplot as plt
from matplotlib.mlab import csv2rec
from matplotlib.cbook import get_sample_data

And then:
filename = "hurricanes-2015.txt"

then :
read_data = csv2rec(filename)
Nothing came up afterwards, so I assumed it was correct. I hope this helped!

**Comment by nanaa9** [comment]
I read in my data using the read function

Ex:
    var_name = open(filename, 'r').readlines()
    var_name = var_name[0].split('\r')
For this data set the deliminator is a return character so I split by '\r'
